import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Hunting-Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={styles.nav}>
        <ul className={styles.mainNav}>
          <li>Home</li>
          <li>About</li>
          <li>Contact</li>
          <li>Blog</li>
        </ul>
      </nav>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <h1 className={styles.title}>Hunting Coder</h1>
          <p className={styles.description}>
            A blog for Hunting coder by a hunting coder.
          </p>
        </main>
        <div className="blogs">
          <h2 className={styles.blogh2}>Popular Blogs: </h2>
          <div className="blogItem">
            <h1 className={styles.blogh1}>How to learn JavaScript in 2025 ?</h1>
            <p>JavaScript is the Language to design logic for web.</p>
          </div>
          <div className="blogItem">
            <h1 className={styles.blogh1}>How to learn JavaScript in 2025 ?</h1>
            <p>JavaScript is the Language to design logic for web.</p>
          </div>
          <div className="blogItem">
            <h1 className={styles.blogh1}>How to learn JavaScript in 2025 ?</h1>
            <p>JavaScript is the Language to design logic for web.</p>
          </div>
          <div className="blogItem">
            <h1 className={styles.blogh1}>How to learn JavaScript in 2025 ?</h1>
            <p>JavaScript is the Language to design logic for web.</p>
          </div>
        </div>
      </div>
    </>
  );
}
